version: '3.8'

services:

  #This container is used to store the data
  postgres_db:
    container_name: postgres_db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: nayren
      POSTGRES_USER: nayren
      POSTGRES_DB: nayren
    ports:
      - "5432:5432"

    volumes:
      - ./postgres-data:/var/lib/postgresql/data #data storage, to keep the data after the container is stopped (need to create the folder before if not exist)

  #This container is used to get the pgadmin
  pgadmin_db:
    container_name: pgadmin_db
    image: dpage/pgadmin4
    restart: always
    ports:
      - "80:80"
    depends_on:
      - postgres_db
    environment:
      PGADMIN_DEFAULT_EMAIL: "nayren@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "nayren"

x-environment:
  COMPOSE_PROJECT_NAME: tp1-dev